/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef FILE_SMF_SEEN
#define FILE_SMF_SEEN

#include <boost/algorithm/string.hpp>
#include <map>
#include <nlohmann/json.hpp>
#include <unordered_set>
#include <vector>

#include "3gpp_24.501.hpp"
#include "3gpp_29.274.h"
#include "3gpp_29.571.h"
#include "Snssai.h"

// From 23.502
enum class session_management_procedures_type_e {
  PROCEDURE_TYPE_UNKNOWN                      = 0,
  PDU_SESSION_ESTABLISHMENT_UE_REQUESTED      = 1,
  SERVICE_REQUEST_UE_TRIGGERED_STEP1          = 2,
  SERVICE_REQUEST_UE_TRIGGERED_STEP2          = 3,
  SERVICE_REQUEST_NETWORK_TRIGGERED           = 4,
  PDU_SESSION_MODIFICATION_UE_INITIATED_STEP1 = 5,
  PDU_SESSION_MODIFICATION_UE_INITIATED_STEP2 = 6,
  PDU_SESSION_MODIFICATION_UE_INITIATED_STEP3 = 7,
  PDU_SESSION_MODIFICATION_SMF_REQUESTED      = 8,
  PDU_SESSION_MODIFICATION_AN_REQUESTED       = 9,
  PDU_SESSION_RELEASE_UE_REQUESTED_STEP1      = 10,
  PDU_SESSION_RELEASE_UE_REQUESTED_STEP2      = 11,
  PDU_SESSION_RELEASE_UE_REQUESTED_STEP3      = 12,
  PDU_SESSION_RELEASE_SMF_INITIATED           = 13,
  PDU_SESSION_RELEASE_AMF_INITIATED           = 14,
  PDU_SESSION_RELEASE_AN_INITIATED            = 15,
  HO_PATH_SWITCH_REQ                          = 16,
  N2_HO_PREPARATION_PHASE_STEP1               = 17,
  N2_HO_PREPARATION_PHASE_STEP2               = 18,
  N2_HO_EXECUTION_PHASE                       = 19,
  N2_HO_CANCELLATION_PHASE                    = 20,
  PDU_SESSION_MODIFICATION_PCF_INITIATED      = 21,
  PDU_SESSION_RELEASE_PCF_INITIATED           = 22,
  DEREGISTRATION_UE_INITIATED                 = 23,
  PDU_SESSION_TEST                            = 24,
  /* The NG-RAN moved the downlink N3 endpoint by itself and told the core
   * about it with a PDU Session Resource Modify Indication. A change of
   * gNB-CU-UP (clause 8.9.5 of TS 38.401) is the case this exists for. */
  PDU_SESSION_MODIFICATION_AN_INDICATED       = 25
};

static const std::vector<std::string> session_management_procedures_type_e2str =
    {"PROCEDURE_TYPE_UNKNOWN",
     "PDU_SESSION_ESTABLISHMENT_UE_REQUESTED",
     "SERVICE_REQUEST_UE_TRIGGERED_STEP1",
     "SERVICE_REQUEST_UE_TRIGGERED_STEP2",
     "SERVICE_REQUEST_NETWORK_TRIGGERED",
     "PDU_SESSION_MODIFICATION_UE_INITIATED_STEP1",
     "PDU_SESSION_MODIFICATION_UE_INITIATED_STEP2",
     "PDU_SESSION_MODIFICATION_UE_INITIATED_STEP3",
     "PDU_SESSION_MODIFICATION_SMF_REQUESTED",
     "PDU_SESSION_MODIFICATION_AN_REQUESTED",
     "PDU_SESSION_RELEASE_UE_REQUESTED_STEP1",
     "PDU_SESSION_RELEASE_UE_REQUESTED_STEP2",
     "PDU_SESSION_RELEASE_UE_REQUESTED_STEP3",
     "PDU_SESSION_RELEASE_SMF_INITIATED",
     "PDU_SESSION_RELEASE_AMF_INITIATED",
     "PDU_SESSION_RELEASE_AN_INITIATED",
     "HO_PATH_SWITCH_REQ",
     "N2_HO_PREPARATION_PHASE_STEP1",
     "N2_HO_PREPARATION_PHASE_STEP2",
     "N2_HO_EXECUTION_PHASE",
     "N2_HO_CANCELLATION_PHASE",
     "PDU_SESSION_MODIFICATION_PCF_INITIATED",
     "PDU_SESSION_RELEASE_PCF_INITIATED",
     /* this vector is indexed with the enum above, so it has to carry every
      * value: DEREGISTRATION_UE_INITIATED was missing, which shifted
      * PDU_SESSION_TEST and left the last entry out of range */
     "DEREGISTRATION_UE_INITIATED",
     "PDU_SESSION_TEST",
     "PDU_SESSION_MODIFICATION_AN_INDICATED"

};

// for N1N2
#define BUF_LEN 2046

// FOR FUTURE PROMISE
#define FUTURE_STATUS_TIMEOUT_MS 100

// for PFCP
constexpr uint64_t SECONDS_SINCE_FIRST_EPOCH = 2208988800;

#define DEFAULT_QFI 1
#define DEFAULT_5QI 9  // TODO: from conf file

#endif
